name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1) Android- & Buildozer-Werkzeuge installieren
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git zip unzip openjdk-17-jdk python3-pip python3-setuptools
        pip install --upgrade cython==0.29.36 buildozer==1.5.0.post0

    # 2) Baue die APK
    - name: Build debug APK
      run: |
        buildozer -v android debug

    # 3) Lade die APK als Artefakt hoch
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: BellAlarm-APK
        path: bin/*.apk
