name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ Checkout repository
      - uses: actions/checkout@v4

      # 2 ▸ Clone Kivy recipe sources
      - name: Clone Kivy recipe sources
        run: |
          git clone https://github.com/kivy/kivy.git \
            --branch 2.2.1 --depth 1 kivy_src

      # 3 ▸ Export P4A_kivy_DIR for python-for-android
      - name: Export P4A_kivy_DIR
        run: echo "P4A_kivy_DIR=$GITHUB_WORKSPACE/kivy_src" >> $GITHUB_ENV

      # 4 ▸ Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 5 ▸ Install Android SDK/NDK & system dependencies (inkl. CPython-Build-Header)
      - name: Install Android SDK/NDK & system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            openjdk-17-jdk \
            python3-pip \
            unzip \
            wget \
            ccache \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            libltdl-dev \
            autoconf-archive \
            pkg-config \
            m4 \
            gettext \
            build-essential \
            libssl-dev \
            libbz2-dev \
            libsqlite3-dev \
            libreadline-dev \
            libffi-dev \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            xz-utils \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libgles2-mesa-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libmtdev-dev \
            libx11-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxi-dev \
            libxss-dev \
            libdbus-1-dev
          export ANDROID_SDK_ROOT="$HOME/android-sdk"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline.zip
          unzip -qq cmdline.zip -d cmdline-tools/tmp
          mv cmdline-tools/tmp/cmdline-tools cmdline-tools/latest
          rm cmdline.zip && rmdir cmdline-tools/tmp
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
          echo "$ANDROID_SDK_ROOT/platform-tools" >> "$GITHUB_PATH"
          mkdir -p "$ANDROID_SDK_ROOT/tools/bin"
          ln -sf "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" "$ANDROID_SDK_ROOT/tools/bin/sdkmanager"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;26.1.10909125"
          yes | sdkmanager --licenses
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> "$GITHUB_ENV"
          echo "ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> "$GITHUB_ENV"

      # 6 ▸ Install Buildozer & Cython
      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade buildozer cython==0.29.36

      # 7 ▸ Purge p4a build dirs
      - name: Purge p4a build dirs
        run: rm -rf ./.buildozer/android/platform/*/build

      # 8 ▸ Build debug APK
      - name: Build debug APK
        id: build_apk
        run: |
          set -o pipefail
          buildozer -v android debug 2>&1 | tee buildozer_full.log

      # 9 ▸ Upload buildozer log
      - name: Upload buildozer log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-log
          path: buildozer_full.log

      # 10 ▸ Upload APK
      - name: Upload APK
        if: steps.build_apk.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: BarkAlarm-APK
          path: bin/*.apk
