name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:       # erlaubt manuelles Starten

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4     # Code holen

    - name: Build with Buildozer
      # ✔ RICHTIGER NAME DER ACTION
      uses: ArtemSBulgakov/buildozer-action@v1   # ← hier lag der Fehler
      with:
        command: "buildozer android debug"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: BellAlarm-APK
        path: bin/*.apk
