name: Build Android APK  # ✔ automatisch bei jedem Push

# Wann der Workflow startet
on:
  push:                 # bei jedem Commit in main
    branches: [ main ]
  workflow_dispatch:    # per Button „Run workflow“ in Actions

jobs:
  build:
    runs-on: ubuntu-latest    # GitHub-Runner (Ubuntu 22.04)

    steps:
    # 1) Projekt auschecken
    - name: Checkout code
      uses: actions/checkout@v4

    # 2) Grundlegende Android- & Buildozer-Werkzeuge installieren
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk python3-pip unzip wget ccache

        # Buildozer + Cython
        pip install --upgrade cython buildozer

        # ----- Android command-line tools (CLI) holen -----
        mkdir -p "$HOME/android-sdk"
        cd "$HOME/android-sdk"
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline.zip
        unzip -qq cmdline.zip
        rm cmdline.zip
        # Struktur so anlegen, wie sdkmanager es erwartet
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/

        # ----- Umgebungsvariablen setzen -----
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools"           >> $GITHUB_PATH

        # ----- Stabile Pakete installieren (API 34, Build-Tools 34.0.0) -----
        yes | sdkmanager --sdk_root="$HOME/android-sdk" \
              "platform-tools" "platforms;android-34" "build-tools;34.0.0"

        # Alle Lizenzen automatisch akzeptieren
        yes | sdkmanager --sdk_root="$HOME/android-sdk" --licenses

    # 3) APK bauen (Debug-Variante)
    - name: Build debug APK
      run: |
        # Buildozer liest ANDROID_SDK_ROOT aus $HOME/android-sdk
        buildozer -v android debug

    # 4) Fertige APK als Artefakt hochladen
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: BellAlarm-APK
        path: bin/*.apk
