name: Build Android APK

on:
  push:
    branches: [ main ]       # bei jedem Commit in main
  workflow_dispatch:         # manueller Button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ Code holen
    - uses: actions/checkout@v4

    # 2 ▸ Java, Python, Buildozer + Android-SDK / NDK installieren
    - name: Install Android & Buildozer tools
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk python3-pip unzip wget ccache

        pip install --upgrade cython buildozer

        # ---------- Android command-line tools ----------
        export ANDROID_SDK_ROOT="$HOME/android-sdk"
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
        cd "$ANDROID_SDK_ROOT"

        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline.zip
        unzip -qq cmdline.zip -d cmdline-tools/tmp
        rm cmdline.zip
        mv cmdline-tools/tmp/cmdline-tools cmdline-tools/latest
        rmdir cmdline-tools/tmp

        # Pfade sofort aktiv
        export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> "$GITHUB_ENV"
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
        echo "$ANDROID_SDK_ROOT/platform-tools"           >> "$GITHUB_PATH"

        # ---------- Plattformen, Build-Tools & NDK ----------
        yes | sdkmanager "platform-tools" \
                         "platforms;android-34" \
                         "build-tools;34.0.0" \
                         "ndk;25.2.9519653"

        # Legacy-Pfad, den Buildozer noch nutzt
        mkdir -p "$ANDROID_SDK_ROOT/tools/bin"
        ln -sf "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
               "$ANDROID_SDK_ROOT/tools/bin/sdkmanager"

        # Alle Lizenzen akzeptieren
        yes | sdkmanager --licenses

    # 3 ▸ Umgebungsvariablen für Buildozer
    - name: Export SDK vars
      run: |
        echo "ANDROID_SDK_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

    # 4 ▸ APK bauen – komplettes Log sichern
    - name: Build debug APK
      id: build_apk
      run: |
        set -o pipefail
        buildozer -v android debug 2>&1 | tee buildozer_full.log

    # 5 ▸ Log immer hochladen
    - name: Upload buildozer log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: buildozer-log
        path: buildozer_full.log

    # 6 ▸ APK nur hochladen, wenn Build erfolgreich
    - name: Upload APK
      if: steps.build_apk.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: BellAlarm-APK
        path: bin/*.apk
